import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, Length, Max, Min, ValidateNested } from 'class-validator';

export enum TripTypeDto { ONE_WAY='ONE_WAY', ROUND_TRIP='ROUND_TRIP', MULTI_CITY='MULTI_CITY' }
export enum CabinDto { ECONOMY='ECONOMY', PREMIUM_ECONOMY='PREMIUM_ECONOMY', BUSINESS='BUSINESS', FIRST='FIRST' }
export enum FlightSortDto { LOWEST_PRICE='LOWEST_PRICE', FASTEST='FASTEST', BEST_VALUE='BEST_VALUE', FEWEST_STOPS='FEWEST_STOPS', EARLIEST_DEPARTURE='EARLIEST_DEPARTURE', LATEST_DEPARTURE='LATEST_DEPARTURE', SHORTEST_LAYOVER='SHORTEST_LAYOVER' }
export class FlightLegDto { @IsString() @Length(3,3) origin!: string; @IsString() @Length(3,3) destination!: string; @IsDateString() departureDate!: string; }
export class FlightSearchDto { @IsEnum(TripTypeDto) tripType!: TripTypeDto; @IsString() @Length(3,3) origin!: string; @IsString() @Length(3,3) destination!: string; @IsDateString() departureDate!: string; @IsOptional() @IsDateString() returnDate?: string; @IsInt() @Min(1) @Max(9) adults!: number; @IsOptional() @IsInt() @Min(0) @Max(9) children?: number; @IsOptional() @IsInt() @Min(0) @Max(9) infants?: number; @IsOptional() @IsEnum(CabinDto) cabin?: CabinDto; @IsOptional() @IsString() @Length(3,3) currency?: string; @IsOptional() @IsBoolean() nonstop?: boolean; @IsOptional() @IsInt() @Min(0) @Max(4) maxStops?: number; @IsOptional() @IsArray() @IsString({ each: true }) airlines?: string[]; @IsOptional() @IsArray() @IsString({ each: true }) alliances?: string[]; @IsOptional() @IsNumber() @Min(0) maxPrice?: number; @IsOptional() @IsInt() @Min(0) maxDurationMinutes?: number; @IsOptional() @IsBoolean() refundableOnly?: boolean; @IsOptional() @IsBoolean() baggageIncluded?: boolean; @IsOptional() @IsEnum(FlightSortDto) sort?: FlightSortDto; }
export class MultiCitySearchDto { @IsArray() @ValidateNested({ each: true }) @Type(() => FlightLegDto) legs!: FlightLegDto[]; @IsInt() @Min(1) @Max(9) adults!: number; @IsOptional() @IsInt() @Min(0) @Max(9) children?: number; @IsOptional() @IsEnum(CabinDto) cabin?: CabinDto; @IsOptional() @IsString() @Length(3,3) currency?: string; }
export class AirportQueryDto { @IsOptional() @IsString() query?: string; @IsOptional() @IsString() country?: string; @IsOptional() @IsString() city?: string; @IsOptional() @IsNumber() latitude?: number; @IsOptional() @IsNumber() longitude?: number; }
export class AirlineQueryDto { @IsOptional() @IsString() query?: string; @IsOptional() @IsString() alliance?: string; @IsOptional() @IsString() country?: string; }
export class TrackRouteDto { @IsString() @Length(3,3) origin!: string; @IsString() @Length(3,3) destination!: string; @IsDateString() departureDate!: string; @IsOptional() @IsDateString() returnDate?: string; @IsOptional() @IsString() @Length(3,3) currency?: string; @IsOptional() @IsNumber() @Min(0) targetPrice?: number; @IsOptional() @IsBoolean() notifyOnDrop?: boolean; }
export class FavoriteRouteDto { @IsString() @Length(3,3) origin!: string; @IsString() @Length(3,3) destination!: string; @IsOptional() @IsString() name?: string; }
