import { Bot, CalendarDays, CreditCard, Plane, ShieldCheck, Sparkles, UsersRound } from 'lucide-react';

const modules = ['Search Flights', 'Compare Prices', 'AI Travel Planning', 'AI Chat Assistant', 'Flight Booking', 'Passenger Management', 'Saved Trips', 'Payments', 'Booking History', 'User Dashboard', 'Admin Dashboard'];
const offers = [{ route: 'JFK → LHR', fare: '$742', note: 'Best balance of price and arrival time' }, { route: 'SFO → HND', fare: '$1,184', note: 'AI recommends 2-day Kyoto extension' }, { route: 'DXB → CDG', fare: '$516', note: 'Refundable fare rules available' }];

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,#1e3a8a,transparent_32%),#020617]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><div className="flex items-center gap-3 text-xl font-black"><span className="grid size-11 place-items-center rounded-2xl bg-gold text-ink"><Plane /></span>NEXARIS TRAVEL AI</div><div className="hidden gap-6 text-sm text-white/70 md:flex"><a href="#platform">Platform</a><a href="#ai">AI</a><a href="#dashboards">Dashboards</a></div><a className="rounded-full bg-white px-5 py-3 text-sm font-bold text-ink" href="#booking">Book flight</a></nav>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-gold/30 bg-gold/10 px-4 py-2 text-sm font-bold text-gold"><Sparkles size={16}/> AI-native travel operations</p><h1 className="max-w-5xl text-6xl font-black tracking-[-0.08em] md:text-8xl">Book smarter trips with an AI travel copilot.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">Search Amadeus-powered flights, optimize budgets, manage passengers, process payments, and give travelers a secure dashboard from one enterprise platform.</p><div className="mt-9 flex flex-wrap gap-4"><a className="rounded-full bg-gold px-6 py-4 font-black text-ink" href="#platform">Explore platform</a><a className="rounded-full border border-white/15 px-6 py-4 font-black" href="#ai">Ask AI assistant</a></div></div><div className="glass rounded-[2rem] p-5"><div className="rounded-[1.5rem] bg-slate-950/80 p-5"><div className="mb-5 flex items-center justify-between"><span className="font-black">Live fare intelligence</span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-sm text-emerald-300">online</span></div>{offers.map((offer)=><div className="mb-3 rounded-3xl border border-white/10 bg-white/[.06] p-4" key={offer.route}><div className="flex items-center justify-between"><strong>{offer.route}</strong><span className="text-2xl font-black text-gold">{offer.fare}</span></div><p className="mt-2 text-sm text-white/60">{offer.note}</p></div>)}</div></div></section>
    <section id="platform" className="mx-auto max-w-7xl px-6 py-16"><div className="mb-8 flex items-end justify-between gap-6"><div><p className="text-sm font-black uppercase tracking-[.2em] text-gold">Platform modules</p><h2 className="mt-3 text-4xl font-black tracking-[-.05em]">Everything needed to operate travel booking.</h2></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modules.map((module)=><div className="glass rounded-3xl p-5" key={module}><ShieldCheck className="mb-4 text-gold"/><h3 className="font-black">{module}</h3><p className="mt-2 text-sm text-white/60">Secure, validated, observable workflow ready for production integrations.</p></div>)}</div></section>
    <section id="ai" className="mx-auto grid max-w-7xl gap-6 px-6 py-16 lg:grid-cols-3"><div className="glass rounded-3xl p-7"><Bot className="mb-4 text-gold"/><h3 className="text-2xl font-black">Conversational planning</h3><p className="mt-3 text-white/65">Structured outputs, function calling, prompt templates, and conversation memory for personalized itineraries.</p></div><div className="glass rounded-3xl p-7"><CreditCard className="mb-4 text-gold"/><h3 className="text-2xl font-black">Payments ready</h3><p className="mt-3 text-white/65">Stripe and Razorpay payment intent, verification, refund, and invoice flows are represented in the architecture.</p></div><div className="glass rounded-3xl p-7"><UsersRound className="mb-4 text-gold"/><h3 className="text-2xl font-black">RBAC dashboards</h3><p className="mt-3 text-white/65">Traveler and admin experiences for bookings, analytics, logs, feature flags, and operations.</p></div></section>
    <section id="booking" className="mx-auto max-w-7xl px-6 py-16"><div className="glass grid gap-8 rounded-[2rem] p-8 lg:grid-cols-2"><div><CalendarDays className="mb-5 text-gold"/><h2 className="text-4xl font-black tracking-[-.05em]">Start with a flight search.</h2><p className="mt-4 text-white/65">The API validates route, dates, cabin, passengers, and currency before provider search or saved-search tracking.</p></div><form className="grid gap-4"><input className="rounded-2xl border border-white/10 bg-white/10 p-4" placeholder="Origin airport (JFK)"/><input className="rounded-2xl border border-white/10 bg-white/10 p-4" placeholder="Destination airport (LHR)"/><button className="rounded-2xl bg-gold p-4 font-black text-ink">Search flights</button></form></div></section>
  </main>;
}
