'use client';
import { useState } from 'react';
import { apiPost } from '../../lib/api';

const steps = ['Offer', 'Passengers', 'Seats', 'Baggage', 'Ancillary', 'Confirm'];
export function BookingStepper() {
  const [step, setStep] = useState(0);
  const [message, setMessage] = useState('');
  async function submit(formData: FormData): Promise<void> {
    const passenger = { firstName: formData.get('firstName'), lastName: formData.get('lastName'), dateOfBirth: formData.get('dateOfBirth'), nationality: formData.get('nationality'), passengerType: 'ADULT', passportNumber: formData.get('passportNumber'), passportExpiry: formData.get('passportExpiry'), mealPreference: formData.get('mealPreference'), wheelchairAssistance: formData.get('wheelchairAssistance') === 'on', specialRequests: formData.get('specialRequests') };
    try { await apiPost('/bookings', { offerId: formData.get('offerId'), contactEmail: formData.get('contactEmail'), contactPhone: formData.get('contactPhone'), passengers: [passenger] }); setMessage('Draft booking created. Continue to payment when ready.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Booking failed'); }
  }
  return <section className="mx-auto max-w-6xl px-6 py-12"><div className="glass rounded-[2rem] p-6"><div className="grid gap-3 md:grid-cols-6">{steps.map((label, index)=><button className={`rounded-2xl p-3 text-sm font-black ${index === step ? 'bg-gold text-ink' : 'bg-white/10 text-white'}`} key={label} onClick={()=>setStep(index)} type="button">{index + 1}. {label}</button>)}</div><form action={submit} className="mt-8 grid gap-5"><div className="grid gap-4 md:grid-cols-2"><input name="offerId" required className="rounded-2xl bg-white/10 p-4" placeholder="Selected offer ID"/><input name="contactEmail" required type="email" className="rounded-2xl bg-white/10 p-4" placeholder="Contact email"/><input name="contactPhone" required className="rounded-2xl bg-white/10 p-4" placeholder="Contact phone"/><input name="firstName" required className="rounded-2xl bg-white/10 p-4" placeholder="Passenger first name"/><input name="lastName" required className="rounded-2xl bg-white/10 p-4" placeholder="Passenger last name"/><input name="dateOfBirth" required type="date" className="rounded-2xl bg-white/10 p-4"/><input name="nationality" required className="rounded-2xl bg-white/10 p-4" placeholder="Nationality"/><input name="passportNumber" className="rounded-2xl bg-white/10 p-4" placeholder="Passport number"/><input name="passportExpiry" type="date" className="rounded-2xl bg-white/10 p-4"/><input name="mealPreference" className="rounded-2xl bg-white/10 p-4" placeholder="Meal preference"/></div><textarea name="specialRequests" className="min-h-28 rounded-2xl bg-white/10 p-4" placeholder="Medical, wheelchair, visa, baggage, or seating requests"/><label className="flex items-center justify-between rounded-2xl bg-white/10 p-4">Wheelchair assistance<input name="wheelchairAssistance" type="checkbox"/></label><button className="rounded-2xl bg-gold p-4 font-black text-ink" type="submit">Create draft booking</button>{message && <p className="rounded-2xl bg-white/10 p-4 text-white/75">{message}</p>}</form></div></section>;
}
