import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsEmail, IsInt, IsNumber, IsOptional, IsString, Length, Max, Min, MinLength, ValidateNested } from 'class-validator';

export class BookingPassengerDto { @IsString() firstName!: string; @IsString() lastName!: string; @IsDateString() dateOfBirth!: string; @IsOptional() @IsString() gender?: string; @IsString() nationality!: string; @IsOptional() @IsString() passportNumber?: string; @IsOptional() @IsDateString() passportExpiry?: string; @IsOptional() visaDetails?: Record<string, string>; @IsString() passengerType!: 'ADULT' | 'CHILD' | 'INFANT'; @IsOptional() emergencyContact?: Record<string, string>; @IsOptional() @IsString() frequentFlyerNumber?: string; @IsOptional() @IsString() mealPreference?: string; @IsOptional() @IsString() medicalAssistance?: string; @IsOptional() @IsBoolean() wheelchairAssistance?: boolean; @IsOptional() @IsString() specialRequests?: string; }
export class CreateBookingDto { @IsString() offerId!: string; @IsArray() @ValidateNested({ each: true }) @Type(() => BookingPassengerDto) passengers!: BookingPassengerDto[]; @IsEmail() contactEmail!: string; @IsString() @MinLength(7) contactPhone!: string; }
export class UpdateBookingDto { @IsOptional() @IsEmail() contactEmail?: string; @IsOptional() @IsString() @MinLength(7) contactPhone?: string; }
export class SeatAssignmentDto { @IsString() passengerId!: string; @IsString() segmentRef!: string; @IsString() seatNumber!: string; @IsString() cabin!: string; @IsOptional() @IsNumber() @Min(0) price?: number; @IsOptional() @IsString() @Length(3,3) currency?: string; @IsOptional() @IsArray() @IsString({ each: true }) characteristics?: string[]; }
export class BaggageSelectionDto { @IsString() passengerId!: string; @IsString() type!: 'CARRY_ON' | 'CHECKED' | 'OVERSIZED' | 'SPORTS_EQUIPMENT' | 'MUSICAL_INSTRUMENT'; @IsInt() @Min(1) @Max(8) quantity!: number; @IsOptional() @IsInt() @Min(1) weightKg?: number; @IsOptional() @IsNumber() @Min(0) price?: number; @IsOptional() @IsString() @Length(3,3) currency?: string; }
export class AncillarySelectionDto { @IsOptional() @IsString() passengerId?: string; @IsString() code!: string; @IsString() name!: string; @IsOptional() @IsNumber() @Min(0) price?: number; @IsOptional() @IsString() @Length(3,3) currency?: string; @IsOptional() metadata?: Record<string, string | number | boolean>; }
export class CancelBookingDto { @IsString() reason!: string; }
